#!/bin/bash
cat grep.sh | awk '{$1=,print $0}'
cat grep.sh | awk '{$1=;print $0}'
cat grep.sh | awk '{$1="";print $0}'
cat test.txt | awk '{print}'
cat test.txt | awk '{$1="";print}'
cat test.txt | awk '{if(NF==1)print}'
cat test.txt | awk '{if(NF==1)print $0}'
cat test.txt | awk '{if(NR==1){print}}'
cat test.txt | awk '{if(NR==1){print $NF}}'
cat test.txt | awk '{if(NR==2){print $NF}}'
cat test.txt | awk '/Thomas/'
cat test.txt | awk '/DBA|Manager/'
cat test.txt | awk '{if(NR==2){print NF}}'
cat test.txt | awk '{if(NR==2){print $(NF-1)}}'
cat test.txt | awk 'BEGIN {c=0} $4 ~/Technology/ {c++;} END {print "number is =",c}'
cat test.txt | awk 'BEGIN {c=0} $4 ~/Technology/ ,NR==2{c++;} END {print "number is =",c}'
cat test.txt | awk 'BEGIN {c=0} $4 ~/Technology/ && NR==2 {c++;} END {print "number is =",c}'
cat test.txt | awk 'BEGIN {c=0} $4 ~/Technology/ || NR==2 {c++;} END {print "number is =",c}'
cat test.txt | awk 'BEGIN {c=0} $4 ~/Technology/ || NR==2 {c++;print NF} END {print "number is =",c}'
cat test.txt | awk 'BEGIN {c=0} $4 ~/Technology/ , NR==2 {c++;print NF} END {print "number is =",c}'